# Generated by Django 4.1.4 on 2023-01-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
